name: Release

on:
  workflow_dispatch:
 
jobs:
  pod-trunk-push:
    runs-on: macOS-12
    steps:
      - uses: maxim-lobanov/setup-xcode@v1.1
        with:
          xcode-version: "13.3"
      - name: Script
        run: echo "Hey"
